### ISSUE TITLE
UI/UX Mockups

### ISSUE THREAD

**Issue by tanerochris** [BuildForSDG/voxnostra#10]
Mockup 10 pages (Landing, home, authentication (login/signup), Project(CRUD), User CRUD
It will be great if more than 10 pages could be designed
The resource to check out  ​[Atomic Design](https://atomicdesign.bradfrost.com/table-of-contents/)

**Comment by tanerochris** [comment]
Hello, what are the updates here?

**Comment by cliffordten** [comment]
Working on mockups
